apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBa5d3zLMZ+4Tl//mNjd/3L4YkJQJYNZK14DAn3CjjD0DiU2PIdZpsNd7Nsbszbn1aFgHtsziDGboCwfwtv3HyxB+a8WJiGCi1FwtDTtYo2SaHWo1dMoTga8tFqT8kHHJt9I1R8wq9vK96qUul6HYwhD5Iwn3tRjuUYO+pOBbdn4t9p0Lw9r3H1Q+05QDJVwW+x5hUr3GR6HJqcPlT6ldQx/kOVlGwcU4gA1BHWdTBnxDSuO/co9og072Xwlv1Nm6ZZL0VKCDxfHm7c4WK0/HOycypOPXfj6KjkwGcmxYiX3LWdlRR1ivuywp9NWbosUGoACH5aOq/LU2QxSs9vRc65NgNCeXYgotzWR30FvuQh4XAlEOn5PkSt5NFwfGRUC1j4eXOT3PxhcXU5WPKWYWrh7ip7Er/fVqfSB9o0cNqze1Z5dPO1gU4uBlEsfhL6ypSSRxYaD68hFu5lJFA0F2AlOYRnk4PERN7LmUUsiKA7gtUi4Klck6FRW8yq2phBFDWLv6fVrhMfFMn868h7HPOnP08szna/8GfYD6nzMNznOJo77okFOcqXr9Oe7VAPgRkcYG3jd/6Nh5U0nWwNFU85KoYIfcPMVWqzAl60n4uAT8FlRNOHUbn/45uPGi2OtwiUP3l5RTdqAdv42E1KVjhMx3ZQhUF2BrzvufVEwMbafAPpTgTw4YfjTpvsT4skzItsBe09aQm0PWOn0nhxdaPGcSHYH07s3HNOyJKvx6fJctbNCeLc6cRL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

